### ISSUE TITLE
Auto migration path descovery

### ISSUE THREAD

**Issue by matperez** [deesoft/yii2-console#1]
Hello! I've used your contoller to implement auto migration discovery [here](https://gist.github.com/matperez/d03ea70a624dbaa621be). May be you could merge it into your extension?

**Comment by mdmunir** [comment]
How about this

``` php
namespace app\modules\some;

class Module extends \yii\base\Module
{
    /**
     * @inheritDoc
     */
    public function init()
    {
        \Yii::$app->params['dee.migration.path'][] = __DIR__.'/migrations';
    }
}
```

Or if your module are in extension. You can add migration path from bootstrap.

``` php
class Bootstrap implements \yii\base\BootstrapInterface
{
    /**
     * @inheritdoc
     */
    public function bootstrap($app)
    {
        $app->params['dee.migration.path'][] = __DIR__.'/migrations';
    }
}
```

**Comment by matperez** [comment]
Great! It works. Also the module must be bootstrapped otherwise it will not run the init function.
